name: Publish Documentation pages

on:
  push:
    branches: [main]

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          cd customer-app && npm ci
          cd ../notifications && npm ci

      - name: Generate documentation
        run: |
          mkdir -p docs/customer-app docs/notifications

          cd customer-app
          npx @compodoc/compodoc -p tsconfig.json -d ../docs/customer-app --silent
          cd ..

          cd notifications
          npx @compodoc/compodoc -p tsconfig.json -d ../docs/notifications --silent
          cd ..

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
