name: Release Version

on:
  push:
    branches:
      - main  

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build notifications
        run: |
          cd notifications
          npm ci
          npm run build

      - name: Build customer-app
        run: |
          cd customer-app
          npm ci
          npm run build

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          name: "Automated Release ${{ github.run_number }}"
          tag_name: "v1.0.${{ github.run_number }}"
          body: |
            Versión generada automáticamente por push a main.
            Commit: ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
